name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region:  us-east-2

    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./ s3://curtisnix.name --delete

- uses: badsyntax/github-action-aws-cloudfront@master
        name: Invalidate CloudFront Cache
        id: invalidate-cloudfront-cache
        with:
          distribution-id: ${{ secrets.CFDistributionId }}
          aws-region: 'us-east-2'
          origin-prefix: 'root'
          include-origin-prefix: true
          invalidate-paths: '/index.html,/'
          default-root-object: 'index.html'